### ISSUE TITLE
Corrupt zip of 1.8.1.0 release

### ISSUE THREAD

**Issue by DasSkelett** [formicant/CriticalTemperatureGauge#5]
Hey @formicant,
the zip file of the latest release, 1.8.1.0, seems to be corrupted.
NetKAN reports `https://github.com/formicant/CriticalTemperatureGauge/releases/download/1.8.1.0/CriticalTemperatureGauge-1.8.1.0.zip is not a valid ZIP file: Error in step EntryHeader for CriticalTemperatureGauge/CriticalTemperatureGauge.version: Exception during test - 'Central header and local header file name mismatch'`

and if I open it in Ark, it shows the following:
![grafik](https://user-images.githubusercontent.com/28812678/69481959-228da900-0e16-11ea-9569-e014b7ca6051.png)
So the folders don't work correctly.

Can you try to re-zip it (maybe with a different program) and release it again?

**Comment by formicant** [comment]
Thanks!
That zip file has been created using PowerShell Compress-Archive command.
Now, I’ve replaced it with one made by 7zip. NetKAN does not report any error now.

I’ve also updated the CriticalTemperatureGauge.netkan file in the NetKAN repo to include new dependencies.

**Comment by HebaruSan** [comment]
Any chance you could take a look at TrimIndicator next? It has the same issue in its latest release.
